name: Test-Package

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Setup Miniconda
      # You may pin to the exact commit or the version.
      # uses: conda-incubator/setup-miniconda@35d1405e78aa3f784fe3ce9a2eb378d5eeb62169
      uses: conda-incubator/setup-miniconda@v2.1.1
      with:
        channels: bioconda, conda-forge
        use-mamba: true
        environment-file: env.yaml
    - run: bash test/test.sh
        
      
